Move ccache setup and repo cloning/setup to commands, other fixups suggested by Claude

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,6 +4,44 @@ orbs:
   win: circleci/windows@5.1.1
   docker: circleci/docker@3.0.1
 
+commands:
+  clone_repo:
+    parameters:
+      include_external_tests:
+        type: boolean
+        default: true
+    steps:
+      - checkout
+      - run:
+          name: Update submodules
+          command: git submodule update --recursive --init
+      - when:
+          condition: << parameters.include_external_tests >>
+          steps:
+            - attach_workspace:
+                name: Attach workspace with zeek-testing pcaps
+                at: .
+            - run:
+                name: Initialize external testing repos
+                command: ci/init-external-repos.sh
+  setup_ccache:
+    parameters:
+      max_size:
+        type: string
+      path:
+        type: string
+    steps:
+      - run:
+          name: Setup ccache
+          command: |
+            mkdir -p << parameters.path >>
+            ccache --set-config=max_size=<< parameters.max_size >>
+            ccache --set-config=compression=true
+            ccache --set-config=cache_dir=<< parameters.path >>
+            ccache --zero-stats
+            ccache --show-stats
+          shell: bash
+
 jobs:
   # Fetches the zeek-testing test traces either from a cache or the remote host
   # and presents them in a workspace for other build jobs to use. This saves
@@ -44,7 +82,6 @@ jobs:
       - run:
           name: Set extra environment variables
           command: |
-            set +e
             if << parameters.build_arm >>; then
               echo "export PLATFORMS='linux/amd64,linux/arm64'" >> "$BASH_ENV"
             else
@@ -72,6 +109,8 @@ jobs:
       - run:
           name: Check if image exists remotely
           command: |
+            # set +e prevents this script from exiting immediately if one of the commands fails.
+            # By default the commands use pipefail, which is overridden by set +e.
             set +e
             if << parameters.build_arm >>; then
                NUM_LINES=$(docker manifest inspect $FULL_IMAGE_TAG 2>/dev/null | grep -c -E "amd64|arm64")
@@ -148,35 +187,19 @@ jobs:
             for line in ${ZEEK_CIRCLE_EXTRA_ENV}; do
               echo "export ${line}" >> "$BASH_ENV"
             done
-      - checkout
-      - run:
-          name: Update submodules
-          command: git submodule update --recursive --init
+      - clone_repo
       - restore_cache:
           name: Restore ccache directory
           keys:
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}-{{ .Revision }}-
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}-
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-
-      - attach_workspace:
-          name: Attach workspace with zeek-testing pcaps
-          at: .
-      - run:
-          name: Initialize external testing repos
-          command: ci/init-external-repos.sh
-      - run:
-          name: Setup ccache
-          command: |
-            set +e
-            mkdir -p ~/.ccache
-            ccache --set-config=max_size=2G
-            ccache --set-config=compression=true
-            ccache --zero-stats
-            ccache --show-stats
+      - setup_ccache:
+          max_size: 2G
+          path: ~/.ccache
       - run:
           name: Build
           command: ci/build.sh
-          environment:
       - run:
           name: Show ccache statistics
           command: ccache --show-stats
@@ -231,26 +254,21 @@ jobs:
       - run:
           name: Enable git symlinks
           command: git config --global core.symlinks true
-      - checkout:
-          # For some reason the default working path has stuff in it already so it can't clone into
-          # that. Unfortunately that means we have to change the working directory for every other
-          # command.
-          path: zeek
-      - run:
-          name: Update submodules
-          command: git submodule update --recursive --init
-          working_directory: zeek
+      - clone_repo:
+          include_external_tests: false
       - run:
           name: Dump environment info
           command: ci\windows\prepare.cmd
           shell: cmd.exe
-          working_directory: zeek
       - restore_cache:
           name: Restore ccache directory
           keys:
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-
+      - setup_ccache:
+          max_size: 2G
+          path: C:\tmp\zeek-ccache
       - restore_cache:
           name: Restore vcpkg cache
           keys:
@@ -258,18 +276,8 @@ jobs:
             - vcpkg-{{ .Branch }}-
             - vcpkg-
       - run:
-          name: Setup ccache
-          command: |
-            mkdir C:\tmp\zeek-ccache
-            ccache --set-config=max_size=2G
-            ccache --set-config=compression=true
-            ccache --set-config=cache_dir=C:\tmp\zeek-ccache
-            ccache --zero-stats
-            ccache --show-stats
-      - run:
           name: Configure
           command: ci\windows\configure.cmd
-          working_directory: zeek
       - save_cache:
           name: Saving vcpkg build cache
           key: vcpkg-{{ .Branch }}-{{ .Revision }}
@@ -280,7 +288,6 @@ jobs:
       - run:
           name: Build
           command: ci\windows\build.cmd
-          working_directory: zeek
       - save_cache:
           name: Save ccache directory
           key: v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
@@ -289,16 +296,17 @@ jobs:
       - run:
           name: Test
           command: ci/windows/test.cmd
-          working_directory: zeek
 
   macos-build:
     parameters:
-      configure:
+      configure_flags:
         type: string
-        default: --build-type=release --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror --with-krb5=/opt/homebrew/opt/krb5 -D NODEJS_ROOT_DIR=/opt/homebrew/opt/node@24
+        default: --build-type=release --disable-broker-tests --prefix=${ZEEK_CI_WORKING_DIR}/install --ccache --enable-werror --with-krb5=/opt/homebrew/opt/krb5 -D NODEJS_ROOT_DIR=/opt/homebrew/opt/node@24
+      xcode_version:
+        type: string
     environment:
       ZEEK_CI: 1
-      ZEEK_CI_CONFIGURE_FLAGS: << parameters.configure >>
+      ZEEK_CI_CONFIGURE_FLAGS: << parameters.configure_flags >>
       # This is based on the size of the m4pro.medium runner, as specified in Circle's docs at
       # https://circleci.com/docs/guides/execution-managed/using-macos/#available-resource-classes.
       ZEEK_CI_CPUS: 6
@@ -306,48 +314,29 @@ jobs:
       ZEEK_CI_BTEST_RETRIES: 2
       ZEEK_CI_RUNNER_OS: macos
     macos:
-      # TODO: should this be a parameter? Do we care to test on other Xcode versions other than the
-      # latest? See https://circleci.com/docs/guides/execution-managed/using-macos/#supported-xcode-versions-silicon
-      # for other options.
-      xcode: 26.5.0
+      xcode: << parameters.xcode_version >>
     resource_class: m4pro.medium
     steps:
       - run:
           name: Set extra environment variables
           command: |
             echo "export ZEEK_CI_WORKING_DIR=${CIRCLE_WORKING_DIRECTORY}" >> "$BASH_ENV"
-      - checkout
+      - clone_repo
       - run:
           name: Install dependencies
           command: ci/macos/prepare.sh
-      - run:
-          name: Update submodules
-          command: git submodule update --recursive --init
       - restore_cache:
           name: Restore ccache directory
           keys:
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
             - v2-ccache-{{ .Environment.CIRCLE_JOB }}-
-      - attach_workspace:
-          name: Attach workspace with zeek-testing pcaps
-          at: .
-      - run:
-          name: Initialize external testing repos
-          command: ci/init-external-repos.sh
-      - run:
-          name: Setup ccache
-          command: |
-            set +e
-            mkdir -p ~/.ccache
-            ccache --set-config=max_size=2G
-            ccache --set-config=compression=true
-            ccache --zero-stats
-            ccache --show-stats
+      - setup_ccache:
+          max_size: 2G
+          path: ~/.ccache
       - run:
           name: Build
           command: ci/build.sh
-          environment:
       - run:
           name: Show ccache statistics
           command: ccache --show-stats
@@ -364,28 +353,6 @@ jobs:
           path: btest-results
 
 workflows:
-  image-build-testing:
-    when:
-      equal: [ "circleci-project-setup-disabled", << pipeline.git.branch >> ]
-    jobs:
-      # - fetch-test-traces
-      # - create-build-image:
-      #     name: ubuntu-24.04-image
-      #     image_name: ubuntu-24.04
-      #     dockerfile_path: ci/ubuntu-24.04
-      - create-build-image:
-          name: build-image-ubuntu-26.04
-          build_arm: false
-      # - create-build-image:
-      #     name: debian-13-image
-      #     image_name: debian-13
-      #     dockerfile_path: ci/debian-13
-      # - linux-build:
-      #     name: ubuntu-24.04
-      #     docker_image: zeek/zeek-ci:ubuntu-24.04-20251125
-      #     requires: [fetch-test-traces, ubuntu-24.04-image]
-      #     enable_benchmarks: true
-
   circleci-config-testing:
     when:
       equal: [ "circleci-project-setup", << pipeline.git.branch >> ]
@@ -423,9 +390,11 @@ workflows:
 
       - macos-build:
           name: macOS-xcode-26.5
+          xcode_version: "26.5"
           requires: [fetch-test-traces]
       - macos-build:
           name: macOS-xcode-16.4
+          xcode_version: "16.4"
           requires: [fetch-test-traces]
       - linux-build:
           name: alpine
@@ -455,7 +424,7 @@ workflows:
       - linux-build:
           name: debian-13-binary
           docker_image: zeek/zeek-ci:debian-13-20260515
-          configure_flags:  --prefix=$CIRRUS_WORKING_DIR/install --libdir=$CIRRUS_WORKING_DIR/install/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --ccache --enable-werror
+          configure_flags:  --prefix=$ZEEK_CI_WORKING_DIR/install --libdir=$ZEEK_CI_WORKING_DIR/install/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --ccache --enable-werror
           requires: [fetch-test-traces, build-image-debian-13]
       - linux-build:
           name: debian-13-static
@@ -469,7 +438,7 @@ workflows:
       - linux-build:
           name: fedora-44
           docker_image: zeek/zeek-ci:fedora-44-20260515
-          configure_flags:  --prefix=$CIRRUS_WORKING_DIR/install --libdir=$CIRRUS_WORKING_DIR/install/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --ccache --enable-werror
+          configure_flags:  --prefix=$ZEEK_CI_WORKING_DIR/install --libdir=$ZEEK_CI_WORKING_DIR/install/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --ccache --enable-werror
           requires: [fetch-test-traces, build-image-fedora-44]
       - linux-build:
           name: opensuse-leap-16.0
@@ -500,7 +469,7 @@ workflows:
       - linux-build:
           name: ubuntu-24.04-clang-tidy
           docker_image: zeek/zeek-ci:ubuntu-24.04-20260515
-          configure_flags: --build-type=debug --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror --enable-clang-tidy
+          configure_flags: --build-type=debug --disable-broker-tests --prefix=$ZEEK_CI_WORKING_DIR/install --ccache --enable-werror --enable-clang-tidy
           requires: [fetch-test-traces, build-image-ubuntu-24.04]
           extra_env: |
             CC="clang-19"
@@ -509,7 +478,7 @@ workflows:
       - linux-build:
           name: ubuntu-24.04-spicy
           docker_image: zeek/zeek-ci:ubuntu-24.04-20260515
-          configure_flags: --build-type=release --disable-broker-tests --enable-spicy-ssl --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror
+          configure_flags: --build-type=release --disable-broker-tests --enable-spicy-ssl --prefix=$ZEEK_CI_WORKING_DIR/install --ccache --enable-werror
           requires: [fetch-test-traces, build-image-ubuntu-24.04]
           extra_env: |
             ZEEK_CI_PREBUILD_COMMAND="cd auxil/spicy && git fetch && git reset --hard origin/main && git submodule update --init --recursive"
